name: CI/CD Pipeline

# Disparar o workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Definição dos jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout do repositório
    - name: Checkout do código
      uses: actions/checkout@v3

    # Configuração do Node.js
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    # Instalar dependências
    - name: Instalar dependências
      run: npm install

    # Executar testes
    - name: Executar testes com Mocha
      run: mocha src/tests/converter.js

    # Construção de imagem Docker
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Login no DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Construir a imagem Docker
      run: docker build -t meu-usuario/meu-repo:latest .

    - name: Push da imagem para DockerHub
      run: docker push meu-usuario/meu-repo:latest

